
"""
Given:  A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

Solved: Jan. 26, 2021, 3:37 p.m.
"""

def ACGTcounter(seq): 
    """ 
    Counts each nucleotide in seq using .count() and prints them out
    """        
    s = seq.upper()
    nucA = s.count("A")
    nucC = s.count("C")
    nucG = s.count("G")
    nucT = s.count("T")

    print(nucA, nucC, nucG, nucT)

dna = "GCAGTATCGCGACGAAGTATTCTTCTTGTGTATAGCTTGTGAGCACCATTCGTGCTATGACTGCGTTTACAGGGGTTGGCTGGATCATAGATCACGACGAAGCCCGAAGGTAGTTAAGATATCAAACAGCCCAATATGGGGCTAAATACCTGAAAGCTTGCTAAGCTGAACCAATCTCCACGATTACTACAACTATTCGTACAATTGCCCGACGTACTTGTTAATTCTCTCGAATCTAGCTCTGGTCCGCATTAAGCAGATCCATGATTAAAGTATGGACACAGTCTTGCCAACCTCGTAAACTCTGATCTCGGTCCGTAATTATGGAACCCTCTGGCGCCTCCTTGGAACAACATCCACGATGCCATGTCTAATTCCGTAGATCAGGACGTCATCTAGAAATCGGTCCTTGGTTACTGCAAAATTCGCTTGAGACGAAAGATAAGCTAGCTTCAAAGGCTCAACTCGTAATCCCCCAGAGCCACCATGATACCACCAAGCCATGCCTGGATATTAAGCGTGATCTCCAACTTCATTACGCGGCATGGCCCTGACTGCAACATCAAAGATGATACGAATTCGAATGTCACGCAGTGGTCAAGTTCACCCCACAAAATCCGCCGTTCCCGGCCGTGAAATCACCAGGTGGGATCTTACCTGTATTACGCGGAATGCTGTAACTGGCAGGGGAGCTTCGACGTCAGAGCGACACAGGCAGGCAGTCTATCCACCTTTATTGAATTGGGCTAAGACTATTCGCGCCCTAGTGCTGAGCCACACCCTTACTCTGAAATTGGCAACTTGCCTTTAACAGGGAAAGTATCTTTGATCGAT"

ACGTcounter(dna)


          
   




