"""
Given:  A DNA string t having length at most 1000 nt.

Return: The transcribed RNA string of t.

Solved: Jan. 26, 2021, 5:59 p.m.
"""

def transcribe(seq):
    """
    Replaces the nucleotides "T" with "U" in seq using .replace()
    Prints out the transcribed sequence.
    """
    t = seq.upper()
    print(t.replace("T","U"))

dna = "TTCGGCGGTAGCGATGCTCAGGGCAGGAAGGAAAGCAGATCCAATCCACGATTTGAAGGGATTGTAAAGTCAGCTACTACTCGTCCAACATCTCGCAGACTTACGCACGGCTATAGTAGACGTATACCGATCGAAGTATTAGTCACAATCCTATAGCCTAACGGTCGACCGCGCGCGAGGTTTTCGTCTAGGGATTGCCGACGCAAGTTTCGCGATGCAAACGTAACCGCACATCTAGCTTGCCTCTAGATTCGTACTTGCTCCATTTTTGCGAGATTCCGCGGGGGATCAAGTGGTAACGGTAGTCACTGAGGGGCCGTGGGAGGACGGCGGATAGTCTGAGCAATCGGTCTTACCATGATCAGCACGCGTATACTACCCTATGGAACGTCTTATCCATATATGCTTGCCGACTTCTCAAGTATCACTTGATGATGTACCGACATCGGTGGAATATAGATACATTGCGACCATACGGAACAGCACATCAGTTACGTGGTAAACAGGACGTCAGGATTTTGCCGGACCCACAACCCAACACTATTCATATTTGGCCGAGGCGAAAGGTATAGTCGTACGGAAGCACTGTCTCTTTTCCACTTGCACTTACTTAAACCGGCTGAGCTGCGCCACGTTGGATGATGGGGACCTGATACGGTGTTGCGGGGAGTGGCTGACCTAGACCGGTTATCCCAATGGGAAGGCCTGGTGGGTTCTTCTCACTCTGCAAATGCAAATATGATCCTTTACACTGAGCAGCCAGACCCATAATACAAGAAGTAGATGGTTCTTCACACGTCTCTGGTGGTGGTCGCTGGGACACCTTCACTTGGACCCATTAAACCCGACCCGCAGGCGTCCGTGGAGGTCGAATCTACTGAGAACCCAGTCCTCGGTCTTTATCTGAATTGGCCAGACTGGCAGGATTTTTTGAACCAGAATTACAATTCTCCCCCTTATA"

transcribe(dna)


