"""
Given:  Two DNA strings s and t (each of length at most 1 kbp).

Return: All locations of t as a substring of s.

Solved: Oct. 8, 2022, 5:41 p.m.
"""

s = "CTACGATGGTACGATGGTACGATGTACGATGTTGATTACGATGTACGATGTACGATGCCTACGATGTTTCTTACGATGTTACGATGACTACGATGTCTACGATGTACGATGTACGATGTACGATGGCGTGGATACGATGACGCTTGTTTTAGTAGCCTCCTACGATGTACGATGTCAGTTACGATGTTACGATGCCATTACGATGTACGATGTACGATGAGACTGTACGATGCTACGATGAAAAGACGATACGATGATACGATGTACGATGATAACCATCTGGATTACGATGATACGATGCACACGTACGATGTTTCGCGTTACGATGACGGAATACGATGTACGATGTACGATGAGTAATACGATGAATACGATGTACGATGGACCATACGATGGGCGCTACGATGTACGATGCCATTACGATGAGTACGATGTTACGATGGTGTATACGATGTACGATGTTACGATGGACCTACGATGTACGATGCTACGATGCCTACGATGCTACGATGTCCTACGATGCTGTACGATGGCGTACGATGTACGATGCGTTTACGATGCTACGATGTACGATGACTTACGATGCTACGATGAGAAGTTACGATGCTGGTTACGATGCGTTCATACGATGTACGATGGTACGATGTACGATGATGGGATACGATGGTCTTACGATGACCTACGATGAAATTACGATGATAGGTTGGGTACGATGATACTACGATGTACGATGTTACGATGGTTACGATGAAATACGATGTAGTTTACGATGCTACGATGCTACGATGACCGGGCGTTGCATACGATGGTACGATGCTACGATGTTACGATGCGTACGATGACATACGATG"
t = "TACGATGTA"


motif_index = ""

for i in range(0,len(s)):
    subset = s[i:i+len(t)]         #We move len(t) forward in string starting at i.
    if subset == t:
        motif_index = motif_index + str(i+1) + " "
    else:
        pass
    
print(motif_index)

