"""
Input: Two strings, s and t where t is a substring of s.
Output: All locations of t in s.
"""

s = "CTACGATGGTACGATGGTACGATGTACGATGTTGATTACGATGTACGATGTACGATGCCTACGATGTTTCTTACGATGTTACGATGACTACGATGTCTACGATGTACGATGTACGATGTACGATGGCGTGGATACGATGACGCTTGTTTTAGTAGCCTCCTACGATGTACGATGTCAGTTACGATGTTACGATGCCATTACGATGTACGATGTACGATGAGACTGTACGATGCTACGATGAAAAGACGATACGATGATACGATGTACGATGATAACCATCTGGATTACGATGATACGATGCACACGTACGATGTTTCGCGTTACGATGACGGAATACGATGTACGATGTACGATGAGTAATACGATGAATACGATGTACGATGGACCATACGATGGGCGCTACGATGTACGATGCCATTACGATGAGTACGATGTTACGATGGTGTATACGATGTACGATGTTACGATGGACCTACGATGTACGATGCTACGATGCCTACGATGCTACGATGTCCTACGATGCTGTACGATGGCGTACGATGTACGATGCGTTTACGATGCTACGATGTACGATGACTTACGATGCTACGATGAGAAGTTACGATGCTGGTTACGATGCGTTCATACGATGTACGATGGTACGATGTACGATGATGGGATACGATGGTCTTACGATGACCTACGATGAAATTACGATGATAGGTTGGGTACGATGATACTACGATGTACGATGTTACGATGGTTACGATGAAATACGATGTAGTTTACGATGCTACGATGCTACGATGACCGGGCGTTGCATACGATGGTACGATGCTACGATGTTACGATGCGTACGATGACATACGATG"
t = "TACGATGTA"



#i_end =  len(s) - len(t)
motif_index = ""

for i in range(0,len(s)):
    subset = s[i:i+len(t)]    
    if subset == t:
        motif_index = motif_index + str(i+1) + " "
    else:
        pass
    
print(motif_index)


"""
Another users solution, similar to mine.
dna = 'GATATATGCATATACTT'
motif = 'ATAT'

for i in range(len(dna)):
    if dna[i:i+len(motif)] ==  motif:
        print(i+1, end=' ')"""